services:
  - type: web
    name: laudo-internacao
    env: python
    region: sao_paulo
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host=0.0.0.0 --port=10000"
    envVars:
      - key: FLASK_APP
        value: app.py
